/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GymDemoRouteImport } from './routes/gym-demo'
import { Route as CoffeeDemoRouteImport } from './routes/coffee-demo'
import { Route as IndexRouteImport } from './routes/index'

const GymDemoRoute = GymDemoRouteImport.update({
  id: '/gym-demo',
  path: '/gym-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeDemoRoute = CoffeeDemoRouteImport.update({
  id: '/coffee-demo',
  path: '/coffee-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coffee-demo': typeof CoffeeDemoRoute
  '/gym-demo': typeof GymDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coffee-demo': typeof CoffeeDemoRoute
  '/gym-demo': typeof GymDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coffee-demo': typeof CoffeeDemoRoute
  '/gym-demo': typeof GymDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coffee-demo' | '/gym-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coffee-demo' | '/gym-demo'
  id: '__root__' | '/' | '/coffee-demo' | '/gym-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoffeeDemoRoute: typeof CoffeeDemoRoute
  GymDemoRoute: typeof GymDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gym-demo': {
      id: '/gym-demo'
      path: '/gym-demo'
      fullPath: '/gym-demo'
      preLoaderRoute: typeof GymDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee-demo': {
      id: '/coffee-demo'
      path: '/coffee-demo'
      fullPath: '/coffee-demo'
      preLoaderRoute: typeof CoffeeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoffeeDemoRoute: CoffeeDemoRoute,
  GymDemoRoute: GymDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
